### ISSUE TITLE
Links wrong for docs/ index page

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/nmos-render-scripts#52]
There is an extra `docs/` in the all links at e.g.:

https://specs.amwa.tv/is-04/branches/v1.3.x/docs/

This doesn't happen in the dir above  https://specs.amwa.tv/is-04/branches/v1.3.x

or for a release e.g. https://specs.amwa.tv/is-04/releases/v1.3.1/docs/

so it will be probably be related to non-numbered document indexing

**Comment by peterbrightwell** [comment]
Haven't seen this in a while, may have been fixed in related changes.

**Comment by garethsb** [comment]
@peterbrightwell Is it as simple as this line being wrong?
https://github.com/AMWA-TV/nmos-render-scripts/blob/3bcbee61830464937a50cbb3004103be78bb21e5/make-indexes.sh#L65
As far as my 😵 bash reading goes, that inserts `doc/` into the links even for the docs/index?

**Comment by peterbrightwell** [comment]
Yes, have replaced that with a grep in #65
