### ISSUE TITLE
Fix cross-repo schema links

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-render-scripts#61]
https://github.com/AMWA-TV/nmos-render-scripts/blob/e244b41baf052879d15245fcfccd448b288c76be/fix-links.sh#L37

The fact that this is done in two parts makes it hard to make a link to a schema in a different spec, e.g. as wanted in IS-11 to refer to the Resource Core schema in IS-04. Pretty sure links to the other spec's GitHub repo won't work and a correct link to the generated HTML currently gets an extra `with-refs/` inserted.

**Comment by garethsb** [comment]
@peterbrightwell would this work?

```
perl -pi -e 's:/APIs/schemas/([^)]+)\.json:/APIs/schemas/with-refs/$1.json:g; s:\.json\):.html\):g;' "$1"
```

**Comment by peterbrightwell** [comment]
Checked with IS-11 and it fixes <https://github.com/AMWA-TV/is-11/issues/107> on a local render

**Comment by garethsb** [comment]
👍  I wonder if we should make these pattern matches a bit more precise to ensure they only pick up links, i.e. `](`...`.json)`, but I haven't worked out quite how...

**Comment by peterbrightwell** [comment]
I've tried a few more repos (locally) and haven't seen anything break yet

**Comment by garethsb** [comment]
Yeah, I guess it's just a theoretical concern that someone might write `(see foo.json)` in some documentation and we'd render it as `(see foo.html)`.
